# 这是小机器人的配置文件

name: Sync to Public Repo

# 触发条件：当一个以 'v' 开头的标签被创建时运行
on:
  push:
    tags:
      - 'v*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 第一步：把 sglhm 的代码下载到机器人临时的环境里
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取所有历史记录，以便推送标签

      # 第二步：把代码推送到公开仓库 sglhm-cs
      - name: Push to sglhm-cs Repo
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git push https://${{ secrets.PAT }}@github.com/shuyuguang/sglhm-cs.git HEAD:main --force --tags
